<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHDsqLkW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHDsqLkW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHDsqLkW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHDsqLkW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHDsqLkW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HDsqLkW',
    'container.build_id' => 'b2cf11b7',
    'container.build_time' => 1610527832,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHDsqLkW');
