<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTH10x70\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTH10x70/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTH10x70.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTH10x70\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerTH10x70\srcApp_KernelProdContainer([
    'container.build_hash' => 'TH10x70',
    'container.build_id' => 'fb0af2aa',
    'container.build_time' => 1608023075,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTH10x70');
